name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Code-testing-and-Quality-Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Security check
        run: npx snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: "Install Salesforce CLI"
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir ~/sfdx
          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
          ~/sfdx/bin/sfdx version
      - name: Run unit tests
        env:
          SCRATCH_ORG_URL: ${{ vars.SCRATCH_ORG_URL }}
          USERNAME: ${{ vars.USERNAME }}
          SCRATCH_ORG_TOKEN: ${{ secrets.SCRATCH_ORG_TOKEN }}
        run: |
          echo "SCRATCH_ORG_URL : $SCRATCH_ORG_URL"
          ~/sfdx/bin/sfdx config set org-instance-url=$SCRATCH_ORG_URL --global
          sf project deploy start --source-dir force-app --ignore-conflicts --target-org $SCRATCH_ORG_TOKEN
          ~/sfdx/bin/sfdx apex run test -o $SCRATCH_ORG_TOKEN -w 5 -y -r human
      - name: Play game
        env:
          SCRATCH_ORG_TOKEN: ${{ secrets.SCRATCH_ORG_TOKEN }}
        run: echo -e "$(sf apex run -o $SCRATCH_ORG_TOKEN -f cli/cli.apex | grep 'USER_DEBUG' | grep -Eo '".*"' | sed 's/&#124;/|/g')"
      # - name: Run ESLint
      #   run: npm run lint
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
